/**
 * Catalog of bitmap icons generated by `scripts/extract-icons.mjs` from the
 * source illustration sheets in `scripts/icon-source/`. Add a new entry here
 * after running the extractor so `<Icon name="...">` autocompletes.
 *
 * Naming convention:
 *   - `food-*`   — food items / containers (cloche, bag, bowl).
 *   - `ui-*`     — generic UI affordances (search, leaf, location, gauge).
 *   - `status-*` — communicate state (fire, check, warning, tag).
 *   - `action-*` — user-triggered actions (plus, trash, pencil, share).
 *   - `social-*` — third-party brand marks (kept for completeness but
 *                  intentionally NOT exported via `<Icon>` because mixing
 *                  brand logos with our own iconography looks off).
 */

export const ICON_CATALOG = {
  // Food (mega sheet, rows 1-3 partial)
  "food-cloche": { src: "/icons/food-cloche.png", label: "Madopdækning" },
  "food-salad-bowl": { src: "/icons/food-salad-bowl.png", label: "Salatskål" },
  "food-pizza": { src: "/icons/food-pizza.png", label: "Pizza" },
  "food-burger": { src: "/icons/food-burger.png", label: "Burger" },
  "food-takeout-bag": { src: "/icons/food-takeout-bag.png", label: "Takeaway-pose" },
  "food-grocery-bag": { src: "/icons/food-grocery-bag.png", label: "Indkøbspose" },
  "food-rice-bowl": { src: "/icons/food-rice-bowl.png", label: "Ris-skål" },
  "food-taco": { src: "/icons/food-taco.png", label: "Taco" },
  "food-soup-bowl": { src: "/icons/food-soup-bowl.png", label: "Suppeskål" },
  "food-egg": { src: "/icons/food-egg.png", label: "Spejlæg" },
  "food-fish": { src: "/icons/food-fish.png", label: "Fisk" },
  "food-cheese": { src: "/icons/food-cheese.png", label: "Ost" },
  "food-bread": { src: "/icons/food-bread.png", label: "Brød" },
  "food-drink-cup": { src: "/icons/food-drink-cup.png", label: "Drikkebæger" },
  "food-chili": { src: "/icons/food-chili.png", label: "Chili" },
  "food-cupcake": { src: "/icons/food-cupcake.png", label: "Cupcake" },
  "food-steak": { src: "/icons/food-steak.png", label: "Steak" },
  "food-drumstick": { src: "/icons/food-drumstick.png", label: "Kyllingelår" },

  // UI affordances
  "ui-calendar-check": { src: "/icons/ui-calendar-check.png", label: "Kalender" },
  "ui-scale": { src: "/icons/ui-scale.png", label: "Vægt" },
  "ui-heart-solid": { src: "/icons/ui-heart-solid.png", label: "Favorit" },
  "ui-leaf": { src: "/icons/ui-leaf.png", label: "Sundt" },
  "ui-gauge": { src: "/icons/ui-gauge.png", label: "Måler" },
  "ui-search": { src: "/icons/ui-search.png", label: "Søg" },
  "ui-funnel": { src: "/icons/ui-funnel.png", label: "Filter" },
  "ui-sliders": { src: "/icons/ui-sliders.png", label: "Indstillinger" },
  "ui-arrows-up-down": { src: "/icons/ui-arrows-up-down.png", label: "Sortér" },
  "ui-funnel-dollar": { src: "/icons/ui-funnel-dollar.png", label: "Pris-filter" },
  "ui-location-pin": { src: "/icons/ui-location-pin.png", label: "Sted" },
  "ui-sliders-large": { src: "/icons/ui-sliders-large.png", label: "Indstillinger" },

  // Navigation (from the secondary nav sheet — overlaps in concept with `ui-*`
  // above but tuned for app-shell/CTA usage at smaller sizes).
  "nav-home": { src: "/icons/nav-home.png", label: "Hjem" },
  "nav-search": { src: "/icons/nav-search.png", label: "Søg" },
  "nav-heart": { src: "/icons/nav-heart.png", label: "Favorit" },
  "nav-person": { src: "/icons/nav-person.png", label: "Profil" },
  "nav-grid": { src: "/icons/nav-grid.png", label: "Oversigt" },
  "nav-clock": { src: "/icons/nav-clock.png", label: "Tid" },
  "nav-pin": { src: "/icons/nav-pin.png", label: "Sted" },
  "nav-chat": { src: "/icons/nav-chat.png", label: "Chat" },
  "nav-settings": { src: "/icons/nav-settings.png", label: "Indstillinger" },
  // nav-bag (shopping bag) intentionally omitted: HvadMad has no shopping
  // surface and the source rendering has a chroma-key fringe on the handle.

  // Status / decoration
  "status-fire": { src: "/icons/status-fire.png", label: "Hot" },
  "status-star": { src: "/icons/status-star.png", label: "Stjerne" },
  "status-badge-check": { src: "/icons/status-badge-check.png", label: "Verificeret" },
  "status-percent": { src: "/icons/status-percent.png", label: "Procent" },
  "status-clock": { src: "/icons/status-clock.png", label: "Tid" },
  "status-info": { src: "/icons/status-info.png", label: "Info" },
  "status-warning": { src: "/icons/status-warning.png", label: "Advarsel" },
  "status-check-circle": { src: "/icons/status-check-circle.png", label: "OK" },
  "status-x-circle": { src: "/icons/status-x-circle.png", label: "Fejl" },
  "status-tag": { src: "/icons/status-tag.png", label: "Tag" },

  // Actions
  "action-plus-filled": { src: "/icons/action-plus-filled.png", label: "Tilføj" },
  "action-minus": { src: "/icons/action-minus.png", label: "Fjern" },
  "action-check-filled": { src: "/icons/action-check-filled.png", label: "Bekræft" },
  "action-x-circle": { src: "/icons/action-x-circle.png", label: "Annullér" },
  "action-trash": { src: "/icons/action-trash.png", label: "Slet" },
  "action-pencil": { src: "/icons/action-pencil.png", label: "Rediger" },
  "action-share": { src: "/icons/action-share.png", label: "Del" },
  "action-heart-outline": { src: "/icons/action-heart-outline.png", label: "Synes om" },
  "action-download": { src: "/icons/action-download.png", label: "Download" },
  "action-external-link": { src: "/icons/action-external-link.png", label: "Eksternt link" },
} as const satisfies Record<string, { src: string; label: string }>;

export type IconName = keyof typeof ICON_CATALOG;
