-- Seed: Hjemmelavet mad
insert into food_options (name, category, emoji, description) values
('Pasta bolognese', 'hjemmelavet', '🍝', 'Klassisk kødsovs med pasta'),
('Lasagne', 'hjemmelavet', '🫕', 'Lag på lag med bechamel og kødsovs'),
('Kylling i karry', 'hjemmelavet', '🍛', 'Cremet karry med ris'),
('Frikadeller', 'hjemmelavet', '🥩', 'Danske frikadeller med kartofler'),
('Taco', 'hjemmelavet', '🌮', 'Hjemmelavet taco med fyld'),
('Stegt flæsk', 'hjemmelavet', '🥓', 'Med persillesovs og kartofler'),
('Wok med kylling', 'hjemmelavet', '🥘', 'Hurtig wok med grøntsager'),
('Chili con carne', 'hjemmelavet', '🌶️', 'Krydret med bønner og ris'),
('Fiskefrikadeller', 'hjemmelavet', '🐟', 'Med remoulade og rugbrød'),
('Spaghetti carbonara', 'hjemmelavet', '🍝', 'Cremet med bacon og parmesan'),
('Biksemad', 'hjemmelavet', '🍳', 'Stegt med kartofler og løg'),
('Gryderet med oksekød', 'hjemmelavet', '🥘', 'Langtidsstegt og mør'),
('Krebinetter', 'hjemmelavet', '🥩', 'Panerede med brun sovs'),
('Hjemmelavet pizza', 'hjemmelavet', '🍕', 'Med selvvalgt topping'),
('Thai suppe', 'hjemmelavet', '🍜', 'Tom kha gai eller lignende'),
('Risotto', 'hjemmelavet', '🍚', 'Cremet italiensk ris'),
('Broccoli-suppe', 'hjemmelavet', '🥦', 'Cremet suppe med brød'),
('Burger', 'hjemmelavet', '🍔', 'Hjemmelavede bøffer med tilbehør'),
('Forårsruller', 'hjemmelavet', '🥟', 'Sprøde med dip'),
('Æggekage', 'hjemmelavet', '🥚', 'Med bacon og rugbrød'),
('Pulled pork', 'hjemmelavet', '🐷', 'Langtidsstegt med coleslaw'),
('Tikka masala', 'hjemmelavet', '🍛', 'Cremet tomatbaseret karry'),
('Millionbøf', 'hjemmelavet', '🥩', 'Med ris og løg'),
('Kyllingelår i ovn', 'hjemmelavet', '🍗', 'Sprøde med ovnkartofler'),
('Grøntsagslasagne', 'hjemmelavet', '🥬', 'Vegetarisk med spinat'),
('Falafel', 'hjemmelavet', '🧆', 'Med hummus og pitabrød'),
('Medisterpølse', 'hjemmelavet', '🌭', 'Med stuvede kartofler'),
('Torsk i ovn', 'hjemmelavet', '🐟', 'Med citron og grøntsager'),
('Nachos med topping', 'hjemmelavet', '🧀', 'Ovnbagte med ost og salsa'),
('Ramen', 'hjemmelavet', '🍜', 'Japansk nudelsuppe'),
('Flæskesteg', 'hjemmelavet', '🥩', 'Med sprød svær'),
('Pandekager', 'hjemmelavet', '🥞', 'Med fyld eller sødt'),
('Fried rice', 'hjemmelavet', '🍚', 'Stegte ris med æg og grønt'),
('Gyros', 'hjemmelavet', '🥙', 'Krydret kød i wrap'),
('Mac and cheese', 'hjemmelavet', '🧀', 'Cremet ostebaseret pasta'),
('Suppe med boller', 'hjemmelavet', '🍲', 'Klassisk hønsekødssuppe'),
('Salat med kylling', 'hjemmelavet', '🥗', 'Frisk og mættende'),
('Quesadilla', 'hjemmelavet', '🫓', 'Med ost og fyld'),
('Dampet laks', 'hjemmelavet', '🐟', 'Med dild og nye kartofler'),
('Hakket oksekød med pasta', 'hjemmelavet', '🍝', 'Hurtig hverdagsret'),
('Ovnbagt kylling', 'hjemmelavet', '🍗', 'Hel kylling med urter'),
('Pølsemix', 'hjemmelavet', '🌭', 'Pølser med diverse tilbehør'),
('Æggestand', 'hjemmelavet', '🥚', 'Ovnbagt omelette'),
('Kartoffelsuppe', 'hjemmelavet', '🥔', 'Cremet med bacon'),
('Wraps', 'hjemmelavet', '🌯', 'Med kylling eller grønt'),
('Indbagte rødspætter', 'hjemmelavet', '🐟', 'Paneret med citron'),
('Pastasalat', 'hjemmelavet', '🥗', 'Kold med grøntsager og dressing'),
('Burritos', 'hjemmelavet', '🌯', 'Store wraps med ris og bønner'),
('Dhal', 'hjemmelavet', '🍛', 'Indisk linsesuppe'),
('Hakkebøffer', 'hjemmelavet', '🥩', 'Med bløde løg og sovs');

-- Seed: Take-away
insert into food_options (name, category, emoji, description) values
('Pizza', 'takeaway', '🍕', 'Klassisk take-away pizza'),
('Sushi', 'takeaway', '🍣', 'Nigiri, maki eller ruller'),
('Burger', 'takeaway', '🍔', 'Fra burgerjoint'),
('Thai mad', 'takeaway', '🍜', 'Pad thai, karry eller suppe'),
('Indisk', 'takeaway', '🍛', 'Karry, naan og tilbehør'),
('Kinesisk', 'takeaway', '🥡', 'Nudler, ris og wok'),
('Kebab', 'takeaway', '🥙', 'Durüm, falafel eller tallerken'),
('Mexicansk', 'takeaway', '🌮', 'Burrito, taco eller nachos'),
('Vietnamesisk', 'takeaway', '🍜', 'Pho eller bánh mì'),
('Subway / sandwich', 'takeaway', '🥪', 'Lang sandwich med fyld'),
('Poke bowl', 'takeaway', '🥗', 'Hawaiiansk skål med fisk og ris'),
('Shawarma', 'takeaway', '🥙', 'Krydret kød i brød'),
('Fish and chips', 'takeaway', '🐟', 'Sprødstegt fisk med fritter'),
('Ramen', 'takeaway', '🍜', 'Japansk nudelsuppe'),
('Fried chicken', 'takeaway', '🍗', 'Sprødt stegt kylling'),
('Dumplings', 'takeaway', '🥟', 'Dampede eller stegte'),
('Pasta', 'takeaway', '🍝', 'Fra italiensk restaurant'),
('Wings', 'takeaway', '🍗', 'Med dip og sauce'),
('Salat', 'takeaway', '🥗', 'Sund take-away'),
('Smørrebrød', 'takeaway', '🥪', 'Dansk klassiker'),
('Flammekuchen', 'takeaway', '🫓', 'Tynd sprød bund med topping'),
('Koreanisk', 'takeaway', '🍚', 'Bibimbap eller fried chicken'),
('Falafel', 'takeaway', '🧆', 'Med hummus og tilbehør'),
('Hotdog', 'takeaway', '🌭', 'Dansk pølsevogn'),
('Panini', 'takeaway', '🥪', 'Varm presset sandwich'),
('Bagel', 'takeaway', '🥯', 'Med fyld'),
('Tapas', 'takeaway', '🍤', 'Små spanske retter'),
('Wok to-go', 'takeaway', '🥘', 'Hurtig wok-ret'),
('Pita', 'takeaway', '🫓', 'Med kød eller grønt'),
('Açaí bowl', 'takeaway', '🫐', 'Sund smoothie bowl');

-- Seed: Restaurant (køkkentype)
insert into food_options (name, category, emoji, description) values
('Italiensk', 'restaurant', '🇮🇹', 'Pasta, pizza, risotto'),
('Japansk', 'restaurant', '🇯🇵', 'Sushi, ramen, yakitori'),
('Dansk', 'restaurant', '🇩🇰', 'Smørrebrød, stegt flæsk, frikadeller'),
('Mexicansk', 'restaurant', '🇲🇽', 'Tacos, burritos, enchiladas'),
('Thai', 'restaurant', '🇹🇭', 'Karry, pad thai, supper'),
('Fransk', 'restaurant', '🇫🇷', 'Bistro, vin, fromage'),
('Indisk', 'restaurant', '🇮🇳', 'Karry, tandoori, naan'),
('Kinesisk', 'restaurant', '🇨🇳', 'Dim sum, wok, peking and'),
('Græsk', 'restaurant', '🇬🇷', 'Souvlaki, tzatziki, moussaka'),
('Koreansk', 'restaurant', '🇰🇷', 'BBQ, bibimbap, kimchi'),
('Vietnamesisk', 'restaurant', '🇻🇳', 'Pho, bánh mì, forårsruller'),
('Spansk', 'restaurant', '🇪🇸', 'Tapas, paella, churros'),
('Amerikansk', 'restaurant', '🇺🇸', 'Burger, steak, BBQ'),
('Tyrkisk', 'restaurant', '🇹🇷', 'Kebab, meze, baklava'),
('Libanesisk', 'restaurant', '🇱🇧', 'Hummus, falafel, tabbouleh'),
('Peruansk', 'restaurant', '🇵🇪', 'Ceviche, lomo saltado'),
('Etiopisk', 'restaurant', '🇪🇹', 'Injera med diverse stuvninger'),
('Nordisk/Nynordisk', 'restaurant', '🌿', 'Moderne skandinavisk'),
('Steakhouse', 'restaurant', '🥩', 'Kvalitetskød og tilbehør'),
('Seafood', 'restaurant', '🦐', 'Fisk og skaldyr'),
('Vegetarisk/Vegansk', 'restaurant', '🌱', 'Plantebaseret'),
('Brunch', 'restaurant', '🥐', 'Sen morgenmad/tidlig frokost'),
('Buffet', 'restaurant', '🍽️', 'Alt-du-kan-spise'),
('Street food', 'restaurant', '🛒', 'Food market / street food hall'),
('Sushi-restaurant', 'restaurant', '🍣', 'Alt-du-kan-spise sushi');

-- Seed: Køkkentype (generelt)
insert into food_options (name, category, emoji, description) values
('Asiatisk', 'koekkentype', '🥢', 'Bred asiatisk kategori'),
('Europæisk', 'koekkentype', '🇪🇺', 'Vesteuropæisk mad'),
('Mellemøstlig', 'koekkentype', '🧆', 'Arabisk, tyrkisk, persisk'),
('Latinamerikansk', 'koekkentype', '💃', 'Mexicansk, peruansk, brasiliansk'),
('Nordisk', 'koekkentype', '❄️', 'Skandinavisk og dansk'),
('Middelhavet', 'koekkentype', '🫒', 'Græsk, italiensk, spansk'),
('Indisk/Sydasiatisk', 'koekkentype', '🍛', 'Indisk, sri lankansk, pakistansk'),
('Afrikansk', 'koekkentype', '🌍', 'Etiopisk, marokkansk, vestafrikansk'),
('Østeuropæisk', 'koekkentype', '🥟', 'Polsk, russisk, ungarsk'),
('Fusion', 'koekkentype', '🔀', 'Blandede køkkener'),
('Comfort food', 'koekkentype', '🛋️', 'Hjemmelig og mættende'),
('Let og sundt', 'koekkentype', '🥗', 'Lavt kalorieindhold'),
('Krydderstærkt', 'koekkentype', '🌶️', 'For dem der kan lide det stærkt'),
('Kødtungt', 'koekkentype', '🥩', 'Fokus på protein'),
('Vegetarisk', 'koekkentype', '🌱', 'Uden kød');

-- Seed: Hurtig aftensmad
insert into food_options (name, category, emoji, description) values
('Toast med ost', 'hurtig', '🧀', 'Sprødt og hurtigt'),
('Æg og bacon', 'hurtig', '🥚', 'Klassisk og simpelt'),
('Rugbrød med pålæg', 'hurtig', '🍞', 'Dansk aftensmad'),
('Omelet', 'hurtig', '🥚', 'Med grøntsager eller ost'),
('Nudler med sovs', 'hurtig', '🍜', 'Instant eller hurtige nudler'),
('Grilled cheese', 'hurtig', '🧀', 'Stegt sandwich med ost'),
('Avocado toast', 'hurtig', '🥑', 'Med æg eller topping'),
('Suppe fra dåse/pose', 'hurtig', '🥫', 'Opvarmet suppe'),
('Yoghurt med müsli', 'hurtig', '🥣', 'Let og hurtigt'),
('Pita med hummus', 'hurtig', '🫓', 'Hurtigt og mættende'),
('Resteaften', 'hurtig', '♻️', 'Det der er i køleskabet'),
('Boller i karry (dåse)', 'hurtig', '🍛', 'Hurtig opvarmning'),
('Toastbaguette', 'hurtig', '🥖', 'Fyldt og ovnbagt'),
('Salat fra pose', 'hurtig', '🥗', 'Færdigblandet'),
('Tun-sandwich', 'hurtig', '🐟', 'Hurtigt og nemt'),
('Havregrød', 'hurtig', '🥣', 'Varm og mættende'),
('Pitabrød med kylling', 'hurtig', '🥙', 'Restkylling i pita'),
('Pasta med pesto', 'hurtig', '🍝', '10 minutters ret'),
('Brødpizza', 'hurtig', '🍕', 'Pizza på ciabatta'),
('Frugt og nødder', 'hurtig', '🍎', 'Helt simpelt');
